server {
    listen 80;
    server_name v1ktr.nomorepartiessite.ru;

    # нужно для certbot (обязательно оставить)
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # всё остальное → на HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}
server {
    listen 443 ssl;
    server_name v1ktr.nomorepartiessite.ru;

    ssl_certificate /etc/letsencrypt/live/v1ktr.nomorepartiessite.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/v1ktr.nomorepartiessite.ru/privkey.pem;

    root /usr/share/nginx/html;
    index index.html;

    # FRONTEND (React SPA)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # BACKEND API
    location /api/ {
        proxy_pass http://backend:3000/api/;

        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # STATIC CONTENT (если есть файлы с бэка)
    location /content/ {
        proxy_pass http://backend:3000/content/;

        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}